spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springbootpostgreser
    username: springboot
    password: mysecretpassword

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true